#!/usr/bin/env bash

# in makefile m4 will expand PREFIX
# before installation
if [[ -d PREFIX ]]; then
  _prefix='PREFIX'
else
  _prefix=/usr
fi

_source=$(readlink -f "${BASH_SOURCE[0]}")

_vivaldi=$(readlink -f "$(which vivaldi-stable)")
: "${_vivaldi:=$(readlink -f "$(which vivaldi-snapshot)")}"

  : "${_vivaldi:=$(realpath "$(command -v vivaldi-stable)")}"
  : "${_vivaldi:=$(realpath "$(command -v vivaldi-snapshot)")}"
  : "${_vivaldi:=$(realpath "$(command -v vivaldi)")}"

  [[ $_vivaldi ]] || ERX "could not find vivaldi, is it installed?"
  _vivaldi_directory=${_vivaldi%/*}/resources/vivaldi

  _vivaldi_version=$("$_vivaldi" --version 2>/dev/null)
  IFS=. read -rs major minor _ <<< "${_vivaldi_version//[^0-9.]/}"

  if ((major >= 6 && minor >= 2))
    then _browser_html=$_vivaldi_directory/window.html
    else _browser_html=$_vivaldi_directory/browser.html
  fi

  unset _vivaldi_version major minor

  [[ -f $_browser_html ]] || ERX \
    "could not find $_browser_html, is vivaldi installed?"

  readonly _tmp=$(mktemp)
  trap 'rm -f "$_tmp"' EXIT SIGINT

  cp -f "$_browser_html" "$_tmp"

  if [[ -n ${__o[remove]} ]]; then
    removefile "${__o[remove]}"
  else
    addfiles "$@"
  fi

  cp -f "$_tmp" "$_browser_html"

  installhook
  exit 0
}

___source="$(readlink -f "${BASH_SOURCE[0]}")"  #bashbud
___dir="${___source%/*}"                        #bashbud
source "$___dir/init.sh"                        #bashbud
main "${@}"                                     #bashbud
