.nh
.TH VIVALDI\-AUTOINJECT\-CUSTOM\-JS 1 2020\-11\-21 Linux "User Manuals"
.SH NAME
.PP
\fB\fCvivaldi\-autoinject\-custom\-js\fR \- auto inject
custom javascript for vivaldi UI

.SH SYNOPSIS
.PP
.RS

.nf
vivaldi\-autoinject\-custom\-js [\-\-remove|\-r FILENAME] [FILES ...]
vivaldi\-autoinject\-custom\-js \-\-list|\-l
vivaldi\-autoinject\-custom\-js \-\-help|\-h
vivaldi\-autoinject\-custom\-js \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
LONG DESCRIPTION

.SH OPTIONS
.PP
\fB\fC\-\-remove\fR|\fB\fC\-r\fR FILENAME

.PP
\fB\fC\-\-list\fR|\fB\fC\-l\fR

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCsed\fR \fB\fCvivaldi\fR

.PP
budRich https://github.com/budlabs/vivaldi\-autoinject\-custom\-js
\[la]https://github.com/budlabs/vivaldi-autoinject-custom-js\[ra]

.SH SEE ALSO
.PP
bash(1), sed(1),
