#!/bin/bash

main() {

  # in makefile m4 will expand PREFIX
  # before installation
  if [[ -d PREFIX ]]
    then _prefix='PREFIX'
    else _prefix=/usr
  fi

  _data_directory=$_prefix/share/vivaldi-UI-js

  if [[ ${_o[list]} && -d $_data_directory ]]; then
    ls -A "$_data_directory"
    exit
  elif ((EUID)); then
    ERX "script needs to be executed as root (sudo)"
  fi

  : "${_vivaldi:=$(realpath "$(command -v vivaldi-stable)")}"
  : "${_vivaldi:=$(realpath "$(command -v vivaldi-snapshot)")}"
  : "${_vivaldi:=$(realpath "$(command -v vivaldi)")}"

  [[ $_vivaldi ]] || ERX "could not find vivaldi, is it installed?"
  _vivaldi_directory=${_vivaldi%/*}/resources/vivaldi

  _vivaldi_version=$("$_vivaldi" --version 2>/dev/null)
  IFS=. read -rs major minor _ <<< "${_vivaldi_version//[^0-9.]/}"

  if ((major >= 6 && minor >= 2))
    then _browser_html=$_vivaldi_directory/window.html
    else _browser_html=$_vivaldi_directory/browser.html
  fi

  unset _vivaldi_version major minor

  [[ -f $_browser_html ]] || ERX \
    "could not find $_browser_html, is vivaldi installed?"

  _tmp=$(mktemp)
  trap 'rm -f "$_tmp"' EXIT SIGINT

  cp -f "$_browser_html" "$_tmp"

  if [[ -n ${_o[remove]} ]]
    then removefile "${_o[remove]}"
    else addfiles "$@"
  fi

  cp -f "$_tmp" "$_browser_html"

  exit 0
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
