.nh
.TH VIVALDI-AUTOINJECT-CUSTOM-JS-UI  1 2023-08-27 budlabs "User Manuals"
.SH NAME
.PP
vivaldi-autoinject-custom-js-ui - manage custom js UI mods for the vivaldi web browser

.SH USAGE
.PP
\fB\fCvivaldi-autoinject-custom-js-ui [OPTIONS] [FILE...]\fR

.PP
To manually add custom javascript modifications to
the \fBvivaldi\fP web browser one needs to do the
following:

.RS
.IP \(bu 2
Add the javascript file to vivaldis resource directory (on arch this is \fB\fC/opt/vivaldi/resources/vivaldi\fR)
.IP \(bu 2
Add an entry in the windows.html (pre vivaldi 6.2: browser.html) file in the same directory.

.RE

.PP
This is not too complicated, but I have noticed
that when \fBvivaldi\fP is being updated, the
\fB\fCwindows.html\fR file is overwritten, meaning that
step 2 needs to be repeated after every update.

.PP
It also gets a bit messy to manage multiple mods.

.PP
If \fB\fCvivaldi-autoinject-custom-js-ui\fR is launched
without any command line arguments, it will update
the \fB\fCwindows.html\fR file to include all javascript
files located in \fB\fCPREFIX/share/vivaldi-UI-js\fR,
(\fIPREFIX defaults to:\fP \fB\fC/usr\fR). The
\fBvivaldi-UI-js/\fP directory is automatically
created by the script when new mods are added.

.PP
Any files with \fB\fC\&.js\fR extension passed as arguments
will get added or updated.

.SH OPTIONS
.PP
.RS

.nf
-h, --help             | Show help and exit
-l, --list             | Prints all installed js modifications
-r, --remove  FILENAME | Remove FILENAME
-v, --version          | Show version and exit

.fi
.RE

.SH CONTACT
.PP
Send bugs and feature requests to:
.br
github.com/budlabs/vivaldi-autoinject-custom-js-ui/issues

.SH COPYRIGHT
.PP
Copyright (c) 2020-2023, budRich of budlabs
.br
SPDX-License-Identifier: BSD-2-Clause
